### ISSUE TITLE
[windows] panic: interface conversion: interface {} is nil, not bool

### ISSUE THREAD

**Issue by cr1cr1** [reconquest/orgalorg#39]
orgalorg version: 1.2.0
platform: windows x64

```bash
orgalorg -s -u root -y -e -r / -S etc
panic: interface conversion: interface {} is nil, not bool

goroutine 1 [running]:
main.upload(0x8cddb7, 0xc000386780, {0xc000392048, 0x1, 0x1})
        /home/runner/work/orgalorg/orgalorg/main.go:543 +0x566
main.handleSynchronize(0x882b00)
        /home/runner/work/orgalorg/orgalorg/main.go:484 +0x6a7
main.main()
        /home/runner/work/orgalorg/orgalorg/main.go:282 +0x6ef
```

where `etc` is a local directory containing a file

Expected: synchronize `/some/dir/etc/file` to remote `/etc/file`

**Comment by cr1cr1** [comment]
On Ubuntu (WSL) I get:

```bash
orgalorg -s -u root -y -e -r / -S etc
2022-04-17 17:16:39  [INFO]     1/1 sending file: 'etc/tmux.conf'
srv1 bash: /usr/lib/orgalorg/sync: No such file or directory
srv1 bash: /usr/lib/orgalorg/sync: No such file or directory
srv1 bash: /usr/lib/orgalorg/sync: No such file or directory
2022-04-17 17:16:39 [FATAL] failed to run sync command
                            └─ failed to finish sync tool command
                               └─ commands are failed on all 3 nodes
                                  └─ code 127 (3 nodes)
```
